<?php

namespace App\Controllers;

use Psr\Log\LoggerInterface;
use CodeIgniter\HTTP\RequestInterface;
use CodeIgniter\HTTP\ResponseInterface;
use CodeIgniter\RESTful\ResourceController;

class BaseController extends ResourceController
{
    public const path_image_pkl = '/media/pkl/';
    public const path_image_pendaftaran = '/media/pendaftaran/';
    public const path_image_monitoring = '/media/monitoring/';

    public $path_image_pkl;
    public $path_image_pendaftaran;
    public $path_image_monitoring;

    public function initController(RequestInterface $request, ResponseInterface $response, LoggerInterface $logger)
    {
        $this->path_image_pkl         = base_url() . self::path_image_pkl;
        $this->path_image_pendaftaran = base_url() . self::path_image_pendaftaran;
        $this->path_image_monitoring = base_url() . self::path_image_monitoring;
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub
    }

    public function errorToArray($errors)
    {
        foreach ($errors as $error) {
            $e[] = $error;
        }
        return isset($e) ? $e[0] : null;
    }
}
